version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379
    restart: "unless-stopped"
  bot:
    build: .
    depends_on:
      - redis
    links:
      - redis
    restart: "unless-stopped"